name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make_lint_job:
    runs-on: ubuntu-latest
    name: make lint action 
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: actions/php-project-lvl1@v1.0.2
